import "@/styles/globals.css"
import localFont from "next/font/local"
import { headers } from "next/headers"
import AppProvider from "./AppProvider"

type RootProps = {
  children: React.ReactNode
}

const inter = localFont({
  src: "./_fonts/Inter-Regular.woff",
  weight: "400",
  style: "normal"
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({ children }: RootProps) {
  const headerList = headers()
  const isAuthenticated = (headerList.get("x-isAuthenticated") ?? "false") === "true"

  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider isAuthenticated={isAuthenticated}>{children}</AppProvider>
      </body>
    </html>
  )
}
